# Task 1:
1.
Write a function to compute 5/0 and use try/except to catch the exceptions.

In [37]:
def CalculateDiv(): 
            try:
                dividend=int(input("Enter Dividend : "))
                divisior=int(input("Enter Divisior : "))
            except:
                 print("Only numbers allowed")
            else:
                    try:
                        result= dividend/divisior
                    except:
                        print(" %d/%d Can't divide by zero"%(dividend,divisior))
                    else :
                         print("%d/%d=%s"%(dividend,divisior,result))
                    
CalculateDiv()                  
    

Enter Dividend : 6
Enter Divisior : 2
6/2=3.0


2.
Implement a Python program to generate all sentences where subject is in 
["Americans","Indians"] 
and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.

subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

Output should come as below:

Americans play Baseball.

Americans play Cricket.

Americans watch Baseball.

Americans watch Cricket.

Indians play Baseball.

Indians play Cricket.

Indians watch Baseball.

Indians watch Cricket.




In [41]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for sub in subjects :
        for v in verbs:
            for obj in objects :
                print(sub,v,obj, end=".\n")

Americans  play Baseball.
Americans  play Cricket.
Americans  watch Baseball.
Americans  watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


# Task 2:
1.
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.


In [53]:
import numpy as np

def generateMatrix(element,column):
        return np.column_stack([element**(column-1-i) for i in range(column)])

print(generateMatrix(np.array([1, 2, 3, 4,5]),4))

#Using Vendor method
def generateMatrix(element,column):
        return np.vander(element,column)

print("\n Using Vendor Method : \n")
print(generateMatrix(np.array([1, 2, 3, 4,5]),4))    


[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]

 Using Vendor Method : 

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
